// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCadIuu_oDLB_dkkWCR1I-e_qeMs-R0H4',
    appId: '1:372226552212:web:62e701c65dc8710690df81',
    messagingSenderId: '372226552212',
    projectId: 'chit-chat-aef02',
    authDomain: 'chit-chat-aef02.firebaseapp.com',
    storageBucket: 'chit-chat-aef02.appspot.com',
    measurementId: 'G-RM6H9DD86Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYt7Zj3KFm67pd9gzFUqV1fjh6o8-nYSc',
    appId: '1:372226552212:android:e7ba7ff225fdcb9890df81',
    messagingSenderId: '372226552212',
    projectId: 'chit-chat-aef02',
    storageBucket: 'chit-chat-aef02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwezPimGH8pa5pnKYBtqaiHLbssDRz_A',
    appId: '1:372226552212:ios:18601d831f80062690df81',
    messagingSenderId: '372226552212',
    projectId: 'chit-chat-aef02',
    storageBucket: 'chit-chat-aef02.appspot.com',
    iosClientId: '372226552212-842gjllraope8rgcvpc14lbfu2ar0d74.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOwezPimGH8pa5pnKYBtqaiHLbssDRz_A',
    appId: '1:372226552212:ios:18601d831f80062690df81',
    messagingSenderId: '372226552212',
    projectId: 'chit-chat-aef02',
    storageBucket: 'chit-chat-aef02.appspot.com',
    iosClientId: '372226552212-842gjllraope8rgcvpc14lbfu2ar0d74.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );
}
